"""Correct RESERVING_INVENTORY order status typo from order_status

Revision ID: 095b3710a3a4
Revises: 97a698210ecb
Create Date: 2026-09-19 15:01:21.852901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '095b3710a3a4'
down_revision: Union[str, Sequence[str], None] = '97a698210ecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
