"""Correct RESERVING_INVENTORY order status typo from order_status

Revision ID: 89736c5dec4b
Revises: 095b3710a3a4
Create Date: 2026-09-19 15:01:37.853607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89736c5dec4b'
down_revision: Union[str, Sequence[str], None] = '095b3710a3a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DELETE FROM pg_enum WHERE enumtypid='order_status'::regtype AND enumlabel = 'RESERVING_INTENTORY'"
    )
    op.execute(
                "ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'RESERVING_INVENTORY'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
