"""add saga processed events

Revision ID: 8d70c81469cb
Revises: 8b53665fd7b9
Create Date: 2026-09-16 15:10:18.546421

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8d70c81469cb'
down_revision: Union[str, Sequence[str], None] = '8b53665fd7b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    
    op.execute(
        "ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'RESERVING_INTENTORY'"
    )
    op.execute(
    "ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'INVENTORY_RESERVED'"
    )

    op.execute(
        "ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'PAYMENT_PENDING'"
    )

    op.execute(
        "ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'COMPENSATING'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_events')
    # ### end Alembic commands ###
