"""add RESERVING_INVENTORY type to order_status correctly

Revision ID: 97a698210ecb
Revises: f54b1f00ff1c
Create Date: 2026-09-19 14:28:03.448006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97a698210ecb'
down_revision: Union[str, Sequence[str], None] = 'f54b1f00ff1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
