"""Order schema corrections

Revision ID: f54b1f00ff1c
Revises: 08cf64d0cfad
Create Date: 2026-09-19 13:44:41.160101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f54b1f00ff1c'
down_revision: Union[str, Sequence[str], None] = '08cf64d0cfad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
            "ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'RESERVING_INVENTORY'"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
