"""added published_at field for OutboxEvent model

Revision ID: 4fc926d298b5
Revises: 1557c405999c
Create Date: 2026-09-16 18:39:29.085906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fc926d298b5'
down_revision: Union[str, Sequence[str], None] = '1557c405999c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_events', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_outbox_events_published_at'), 'outbox_events', ['published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_events_published_at'), table_name='outbox_events')
    op.drop_column('outbox_events', 'published_at')
    # ### end Alembic commands ###
